language: swift
os: osx
osx_image: xcode11.2
xcode_workspace: GoldPrice.xcworkspace

matrix:
  include:
    - xcode_scheme: GoldPrice-iOS
      xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 11 Pro

    - xcode_scheme: GoldPrice-tvOS
      code_destination: platform=tvOS Simulator,OS=13.0,name=Apple TV 4K
